const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const K={people:'crm_people_v2',stores:'crm_stores_v2',acts:'crm_activity_catalog_v2',live:'crm_live_v2',hist:'crm_activity_history_v2',fu:'crm_followups_v2',team:'crm_team_v2'};
const defaults=['GUÍA DE REMESAS','SEGUIMIENTO ACTIVACIÓN','REVISIÓN BPI','LLAMADA DE ATENCIÓN','CAPACITACIÓN','CARTA DE AMONESTACIÓN','REVISIÓN DE INCIDENCIAS','CONTACTO CON TIENDA'];
let people=JSON.parse(localStorage.getItem(K.people)||'null')||window.INITIAL_PEOPLE||[];
let stores=JSON.parse(localStorage.getItem(K.stores)||'null')||window.INITIAL_STORES||[];
let activities=JSON.parse(localStorage.getItem(K.acts)||'null')||defaults;
let live=JSON.parse(localStorage.getItem(K.live)||'[]'), history=JSON.parse(localStorage.getItem(K.hist)||'[]'), followups=JSON.parse(localStorage.getItem(K.fu)||'[]');
let team=JSON.parse(localStorage.getItem(K.team)||'null')||['MARIELA','MAFER','JULIA','ALE'];
let selectedAssistants=[], selectedFuPerson=null, selectedPromoter=null, chart=null;
const save=()=>{localStorage.setItem(K.people,JSON.stringify(people));localStorage.setItem(K.stores,JSON.stringify(stores));localStorage.setItem(K.acts,JSON.stringify(activities));localStorage.setItem(K.live,JSON.stringify(live));localStorage.setItem(K.hist,JSON.stringify(history));localStorage.setItem(K.fu,JSON.stringify(followups));localStorage.setItem(K.team,JSON.stringify(team));};
const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)};
const fmt=d=>new Date(d).toLocaleString('es-MX',{dateStyle:'short',timeStyle:'short'});
const mins=(a,b)=>Math.max(1,Math.round((new Date(b)-new Date(a))/60000));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function init(){bindTabs();refreshCatalogUI();renderAll();setInterval(()=>{$('#clock').textContent=new Date().toLocaleString('es-MX')},1000);$('#clock').textContent=new Date().toLocaleString('es-MX');}
function bindTabs(){$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+b.dataset.view).classList.add('active');if(b.dataset.view==='estadisticas')renderStats();});}
function refreshCatalogUI(){const owners=[...new Set(team)].sort();['#activityOwner','#fuOwner'].forEach(id=>{$(id).innerHTML=owners.map(x=>`<option>${esc(x)}</option>`).join('')});$('#activityType').innerHTML=activities.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')+'<option value="__manual">+ AGREGAR ACTIVIDAD MANUAL</option>';$('#fuType').innerHTML=['SEGUIMIENTO ACTIVACIÓN','LLAMADA DE ATENCIÓN','RETROALIMENTACIÓN','CAPACITACIÓN','CARTA DE AMONESTACIÓN','REVISIÓN','SEGUIMIENTO POSITIVO','OTRO'].map(x=>`<option>${x}</option>`).join('');let regs=[...new Set(stores.map(s=>s.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));['#activityRegion','#fuRegion'].forEach(id=>$(id).innerHTML='<option value="">Selecciona...</option>'+regs.map(r=>`<option>${esc(r)}</option>`).join(''));$('#storesList').innerHTML=stores.map(s=>`<option value="${esc(s.det+' — '+s.partner+' '+s.name+' — '+s.region)}"></option>`).join('');$('#activityCatalogChips').innerHTML=activities.map((a,i)=>`<span class="chip">${esc(a)} <button data-delact="${i}">×</button></span>`).join('');$$('[data-delact]').forEach(b=>b.onclick=()=>{activities.splice(+b.dataset.delact,1);save();refreshCatalogUI();});}
$('#activityType').onchange=e=>$('#manualActivityWrap').classList.toggle('hidden',e.target.value!=='__manual');
$('#activityScope').onchange=e=>{const v=e.target.value;$('#storeWrap').classList.toggle('hidden',v!=='store');$('#regionWrap').classList.toggle('hidden',v!=='region');selectedAssistants=[];renderAssistantChips();};
function searchPeople(q,scope,store,region){q=q.trim().toUpperCase();let arr=people.filter(p=>!q||p.name.includes(q)||(p.user||'').toUpperCase().includes(q));if(scope==='store'){const d=(store.match(/^\s*([0-9]+)/)||[])[1];if(d)arr=arr.filter(p=>p.store===d)}if(scope==='region'&&region)arr=arr.filter(p=>p.region===region);return arr.sort((a,b)=>(a.status==='ACTIVO'?-1:1)-(b.status==='ACTIVO'?-1:1)||a.name.localeCompare(b.name)).slice(0,12)}
function bindPersonSearch(input,res,callback,filterFn){input.oninput=()=>{let arr=(filterFn?filterFn(input.value):searchPeople(input.value));res.innerHTML=arr.map((p,i)=>`<div class="result" data-i="${i}"><b>${esc(p.name)}</b><small>${esc(p.status)} · ${esc(p.store||'SIN TIENDA')} · ${esc(p.region||'')}</small></div>`).join('')+(`<div class="result" data-manual="1"><b>+ Agregar manualmente “${esc(input.value||'PERSONA')}”</b><small>No está en el catálogo actual</small></div>`);res.classList.add('show');[...res.querySelectorAll('[data-i]')].forEach(el=>el.onclick=()=>{callback(arr[+el.dataset.i]);res.classList.remove('show');input.value=''});res.querySelector('[data-manual]').onclick=()=>{const n=(input.value||prompt('Nombre completo:')||'').trim().toUpperCase();if(!n)return;const p={name:n,user:'',status:'MANUAL',role:'',store:'',storeName:'',region:'',source:'MANUAL'};people.unshift(p);save();callback(p);res.classList.remove('show');input.value='';toast('Persona manual agregada');};};}
bindPersonSearch($('#assistantSearch'),$('#assistantResults'),p=>{if(!selectedAssistants.some(x=>x.name===p.name))selectedAssistants.push(p);renderAssistantChips();},q=>searchPeople(q,$('#activityScope').value,$('#activityStore').value,$('#activityRegion').value));
function renderAssistantChips(){$('#selectedAssistants').innerHTML=selectedAssistants.map((p,i)=>`<span class="chip">${esc(p.name)} <button data-rm="${i}">×</button></span>`).join('');$$('[data-rm]').forEach(b=>b.onclick=()=>{selectedAssistants.splice(+b.dataset.rm,1);renderAssistantChips();});}
bindPersonSearch($('#fuPerson'),$('#fuPersonResults'),p=>{selectedFuPerson=p;$('#fuPerson').value=p.name;if(!$('#fuStore').value&&p.store){const s=stores.find(x=>x.det===p.store);$('#fuStore').value=s?`${s.det} — ${s.partner} ${s.name} — ${s.region}`:p.store;}if(p.region)$('#fuRegion').value=p.region;});
bindPersonSearch($('#promoterSearch'),$('#promoterResults'),p=>{selectedPromoter=p;$('#promoterSearch').value=p.name;renderPromoter();});
$('#startActivity').onclick=()=>{const owner=$('#activityOwner').value;let type=$('#activityType').value==='__manual'?$('#manualActivity').value.trim().toUpperCase():$('#activityType').value;if(!type)return toast('Escribe la actividad');if(live.some(x=>x.owner===owner))return toast(owner+' ya tiene una actividad activa');if(!activities.includes(type)){activities.push(type);refreshCatalogUI()}const scope=$('#activityScope').value;const store=$('#activityStore').value.trim(),region=$('#activityRegion').value;const rec={id:crypto.randomUUID(),owner,type,scope,store:scope==='store'?store:'',region:scope==='region'?region:'',assistants:selectedAssistants.map(p=>p.name),note:$('#activityNote').value.trim(),start:new Date().toISOString()};live.push(rec);save();selectedAssistants=[];renderAssistantChips();renderAll();toast('Actividad iniciada');};
$('#finishMine').onclick=()=>{const owner=$('#activityOwner').value;const i=live.findIndex(x=>x.owner===owner);if(i<0)return toast('No hay actividad activa para '+owner);const rec=live.splice(i,1)[0];rec.end=new Date().toISOString();history.unshift(rec);save();renderAll();toast('Actividad finalizada');};
function renderLive(){const c=$('#liveCards');c.innerHTML=live.map(x=>`<div class="card"><span class="badge">EN CURSO</span><h3>${esc(x.owner)}</h3><b>${esc(x.type)}</b>${x.store?`<div class="meta">🏪 ${esc(x.store)}</div>`:''}${x.region?`<div class="meta">📍 ${esc(x.region)}</div>`:''}${x.assistants.length?`<div class="meta">👥 ${x.assistants.length} asistentes</div>`:''}<div class="meta">Desde ${fmt(x.start)}</div>${x.note?`<div class="meta">📝 ${esc(x.note)}</div>`:''}</div>`).join('');$('#liveEmpty').style.display=live.length?'none':'block';}
function renderRecent(){$('#recentActivities').innerHTML=history.slice(0,8).map(x=>`<div class="event"><div class="row"><b>${esc(x.owner)} · ${esc(x.type)}</b><small>${fmt(x.start)}</small></div><small>${x.end?mins(x.start,x.end)+' min':''} ${esc(x.store||x.region||'')}</small></div>`).join('')||'<div class="empty">Sin historial todavía.</div>';$('#recentFollowups').innerHTML=followups.slice(0,8).map(x=>`<div class="event"><div class="row"><b>${esc(x.promoter)} · ${esc(x.type)}</b><small>${fmt(x.date)}</small></div><small>${esc(x.owner)} · ${esc(x.store||x.region||'')}</small></div>`).join('')||'<div class="empty">Sin seguimientos todavía.</div>';}
async function db(){return new Promise((ok,no)=>{const r=indexedDB.open('MesaControlCRMFiles',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});}
async function putFile(file){const id=crypto.randomUUID(),d=await db();return new Promise((ok,no)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=()=>ok({id,name:file.name,type:file.type});tx.onerror=()=>no(tx.error)})}
async function getFile(id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction('files').objectStore('files').get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
$('#saveFollowup').onclick=async()=>{if(!selectedFuPerson)return toast('Selecciona un promotor');const files=[];for(const f of $('#fuEvidence').files)files.push(await putFile(f));const rec={id:crypto.randomUUID(),date:new Date().toISOString(),owner:$('#fuOwner').value,promoter:selectedFuPerson.name,user:selectedFuPerson.user||'',store:$('#fuStore').value.trim(),region:$('#fuRegion').value,type:$('#fuType').value,reason:$('#fuReason').value.trim(),comment:$('#fuComment').value.trim(),evidence:files};followups.unshift(rec);save();$('#fuComment').value='';$('#fuReason').value='';$('#fuEvidence').value='';renderAll();toast('Seguimiento guardado');};
async function evidenceHTML(list,holder){holder.innerHTML='';for(const e of list||[]){const f=await getFile(e.id);if(!f)continue;const url=URL.createObjectURL(f);if((e.type||'').startsWith('image/'))holder.insertAdjacentHTML('beforeend',`<a href="${url}" target="_blank"><img src="${url}" alt="evidencia"></a>`);else holder.insertAdjacentHTML('beforeend',`<a class="file-link" href="${url}" target="_blank">📎 ${esc(e.name)}</a>`);}}
function renderPromoter(){if(!selectedPromoter)return;const p=selectedPromoter;$('#promoterProfile').classList.remove('hidden');$('#promoterProfile').innerHTML=`<h2>${esc(p.name)}</h2><div><b>Usuario:</b> ${esc(p.user||'—')} · <b>Estatus:</b> ${esc(p.status||'—')} · <b>Tienda actual:</b> ${esc(p.store||'—')} ${esc(p.storeName||'')} · <b>Región:</b> ${esc(p.region||'—')}</div>`;const arr=followups.filter(x=>x.promoter===p.name);$('#promoterTimeline').innerHTML=arr.map(x=>`<div class="event"><div class="row"><b>${esc(x.owner)} · ${esc(x.type)}</b><small>${fmt(x.date)}</small></div><div class="meta">${esc(x.store||x.region||'')} ${x.reason?'· '+esc(x.reason):''}</div>${x.comment?`<p>${esc(x.comment)}</p>`:''}<div class="evidence" id="ev-${x.id}"></div></div>`).join('')||'<div class="empty">Este promotor todavía no tiene seguimientos.</div>';arr.forEach(x=>evidenceHTML(x.evidence,$('#ev-'+x.id)));}
function renderStats(){const totals={};history.filter(x=>x.end).forEach(x=>totals[x.type]=(totals[x.type]||0)+mins(x.start,x.end));const labels=Object.keys(totals),data=Object.values(totals);if(chart)chart.destroy();chart=new Chart($('#activityChart'),{type:'doughnut',data:{labels,datasets:[{data}]},options:{plugins:{legend:{position:'bottom'}},maintainAspectRatio:false}});const scopes={};history.filter(x=>x.end).forEach(x=>{const k=x.store||x.region||'SIN ALCANCE';scopes[k]=(scopes[k]||0)+mins(x.start,x.end)});const max=Math.max(1,...Object.values(scopes));$('#scopeStats').innerHTML=Object.entries(scopes).sort((a,b)=>b[1]-a[1]).slice(0,15).map(([k,v])=>`<div class="barrow"><span>${esc(k)}</span><div class="bar"><span style="width:${v/max*100}%"></span></div><b>${v} min</b></div>`).join('')||'<div class="empty">Finaliza actividades para generar estadísticas.</div>';}
function renderAll(){renderLive();renderRecent();if(selectedPromoter)renderPromoter();}
$('#addActivityCatalog').onclick=()=>{const v=$('#newActivityCatalog').value.trim().toUpperCase();if(v&&!activities.includes(v)){activities.push(v);save();refreshCatalogUI();$('#newActivityCatalog').value='';toast('Actividad agregada')}};
async function readWorkbook(file){const buf=await file.arrayBuffer();return XLSX.read(buf,{type:'array'});}
function rowObjects(ws){return XLSX.utils.sheet_to_json(ws,{defval:''});}
$('#loadAttendance').onclick=async()=>{const f=$('#attendanceFile').files[0];if(!f)return toast('Selecciona un archivo');try{const wb=await readWorkbook(f);const ws=wb.Sheets[wb.SheetNames[0]];const rows=rowObjects(ws);const norm=k=>String(k).trim().replace(/\s+/g,' ').toUpperCase();const next=[];rows.forEach(r=>{const map={};Object.keys(r).forEach(k=>map[norm(k)]=r[k]);const name=String(map['NOMBRE COMPLETO']||'').trim();if(!name)return;next.push({name:name.toUpperCase(),user:String(map['USUARIO']||'').trim(),status:String(map['ESTATUS']||'').trim().toUpperCase(),role:String(map['PERFIL DE PUESTO BANCO']||map['PERFIL DE PUESTO\nBANCO']||'').trim().toUpperCase(),store:String(map['DETERMINANTE']||'').replace(/\.0$/,''),storeName:String(map['NOMBRE DE LA TIENDA']||'').trim().toUpperCase(),region:String(map['REGION']||'').trim().toUpperCase(),source:'ASISTENCIA'});});if(!next.length)throw Error('No se encontró NOMBRE COMPLETO');const manual=people.filter(p=>p.source==='MANUAL'&&!next.some(n=>n.name===p.name));people=[...next,...manual];save();$('#attendanceStatus').textContent=`${next.length} personas cargadas · ${new Date().toLocaleString('es-MX')}`;toast('ASISTENCIA actualizada');}catch(e){toast('No pude leer ASISTENCIA: '+e.message)}};
$('#loadStores').onclick=async()=>{const f=$('#storesFile').files[0];if(!f)return toast('Selecciona un archivo');try{const wb=await readWorkbook(f);const ws=wb.Sheets[wb.SheetNames.find(n=>n.toUpperCase().includes('BASE DE TIENDAS INVEX'))||wb.SheetNames[0]];const rows=rowObjects(ws),next=[];rows.forEach(r=>{const keys=Object.fromEntries(Object.keys(r).map(k=>[k.trim().toUpperCase(),r[k]]));const det=String(keys['NUMERO DE TIENDA/DETERMINANTE']||keys['DETERMINANTE']||'').replace(/\.0$/,'').trim();if(!det)return;next.push({det,name:String(keys['TIENDA']||'').trim().toUpperCase(),partner:String(keys['SOCIO']||'').trim().toUpperCase(),region:String(keys['REGION']||'').trim().toUpperCase(),state:String(keys['ESTADO']||'').trim().toUpperCase(),city:String(keys['CIUDAD']||'').trim().toUpperCase(),status:String(keys['ESTATUS']||'').trim().toUpperCase()});});if(!next.length)throw Error('No se encontraron tiendas');stores=next;save();refreshCatalogUI();$('#storesStatus').textContent=`${next.length} tiendas cargadas · ${new Date().toLocaleString('es-MX')}`;toast('BASE DE TIENDAS actualizada');}catch(e){toast('No pude leer tiendas: '+e.message)}};
init();
